import wptSmall from "./images/wpt/wptSmall.png";
import wptMedium from "./images/wpt/wptMedium.png";
import wptLarge from "./images/iskender/iskender.png";
import wptXL from "./images/wpt/wptXl.png";

import pitbike from './images/pitbike/pitbike.webp'
import funny from './images/funny/911a01b4d41d1a6425ed043333018f2d04d821b5-1691002812.webp'
import funny2 from './images/funny/d8838f9d2d2649d7a0499dc2e39f8ebec2f3c444-1691002815.webp'
import uxui from './images/uxui/e0f013d976409cb9ded0e55192257d5fb680b71d-1677168967.webp'
import laser from './images/laser/laser.png'
import legce from './images/legce/desktop.png'
import mnu from './images/mnu/screencapture-wonderful-selkie-bae770-netlify-app-2024-03-11-02_20_35.png'
import oss from './images/oss/d9b427fd44abaf2a4ecc4072ad3ae89764165878-1677168967.webp'
import projects from './images/Arduino-Projects.jpg'
import mentor from './images/mentor/photo_2024-03-11_02-52-47.jpg'

import GitHub from "@mui/icons-material/GitHub";
import LinkedIn from "@mui/icons-material/LinkedIn";

//Portfolio => desc Recomended 300 characters.

const data = {
  portfolio: [
    {
      name: "https://iskender.kg/home",
      title: "Iskender Furniture",
      isKwork: true,
      haveLink: true,
      subtitle:
        "Delivering a robust dashboard and interactive capabilities for efficient warehouse management",
      featured: true,
      url: "https://warehouse-planning-tool.onrender.com/",
      github: "https://github.com/AleksandrRiabov/wpt",
      technologies: [
        "React.Js",
        "TypeScript",
        "Node.Js (Express)",
        "MongoDB Atlas",
        "MaterialUI",
        "Recharts.js",
        "Date-fns",
        "react-router",
        "Firebase Authentication",
        "Deployed on render.com",
      ],
      imgSmall: wptSmall,
      imgMedium: wptMedium,
      imgLarge: wptLarge,
      imgXl: wptXL,
      desc: "Проект “e-commerce сайт по продаже мебели”. Выполнил несколько больших тасков: плейсхолдеры для всех видов данных на сайте, корзина обычного пользователя и корзина менеджера, верстка на мобильной версии",
      paragraphs: [
        "In the dynamic world of logistics, warehouses often collaborate with external distributors, emphasizing the need for timely trailer requests. This demands foresight, striking a balance between excess and shortage. The WPT app offers a visionary solution, reshaping estimation accuracy. Embrace this shift, take immediate action, and eliminate uncertainties in trailer requisition.",
      ],
    },
    {
      name: "",
      title: "Менторство в школе CODE",
      isKwork: true,
      haveLink: false,
      subtitle:
        "Delivering a robust dashboard and interactive capabilities for efficient warehouse management",
      featured: true,
      url: "https://warehouse-planning-tool.onrender.com/",
      github: "https://github.com/AleksandrRiabov/wpt",
      technologies: [
        "React.Js",
        "TypeScript",
        "Node.Js (Express)",
        "MongoDB Atlas",
        "MaterialUI",
        "Recharts.js",
        "Date-fns",
        "react-router",
        "Firebase Authentication",
        "Deployed on render.com",
      ],
      imgSmall: wptSmall,
      imgMedium: wptMedium,
      imgLarge: mentor,
      imgXl: wptXL,
      desc: "В ходе менторства в школе программирования я улучшил не только свои технические навыки, но и значительно развил социальные компетенции. За год работы я провел обучение четырёх групп студентов по 8 месяцев в каждой. Со всеми учениками удалось поддержать дружеские отношения. Моя коммуникабельность и нетерпение к скучным урокам сыграли важную роль в этом процессе.",
      paragraphs: [
        "In the dynamic world of logistics, warehouses often collaborate with external distributors, emphasizing the need for timely trailer requests. This demands foresight, striking a balance between excess and shortage. The WPT app offers a visionary solution, reshaping estimation accuracy. Embrace this shift, take immediate action, and eliminate uncertainties in trailer requisition.",
      ],
    },
    {
      name: "https://precious-gelato-fff9ee.netlify.app/",
      title: "Pitbike Club CRM",
      haveLink: true,
      subtitle:
        "Delivering a robust dashboard and interactive capabilities for efficient warehouse management",
      featured: true,
      url: "https://warehouse-planning-tool.onrender.com/",
      github: "https://github.com/AleksandrRiabov/wpt",
      technologies: [
        "React.Js",
        "TypeScript",
        "Node.Js (Express)",
        "MongoDB Atlas",
        "MaterialUI",
        "Recharts.js",
        "Date-fns",
        "react-router",
        "Firebase Authentication",
        "Deployed on render.com",
      ],
      imgSmall: wptSmall,
      imgMedium: wptMedium,
      imgLarge: pitbike,
      imgXl: wptXL,
      desc: "Выполнил таск на верстку страницы CRM придерживаясь методологии БЭМ и используя свою систему компонентов на SCSS ",
      paragraphs: [
        "In the dynamic world of logistics, warehouses often collaborate with external distributors, emphasizing the need for timely trailer requests. This demands foresight, striking a balance between excess and shortage. The WPT app offers a visionary solution, reshaping estimation accuracy. Embrace this shift, take immediate action, and eliminate uncertainties in trailer requisition.",
      ],
    },
    {
      name: "",
      title: "JavaScript и React PET-проекты",
      isKwork: true,
      haveLink: false,
      isPetList: true,
      petList: [
        {name: "JS: Калькулятор", link: "https://calculatoreval.netlify.app/"},
        {name: "JS: Часы со стрелками", link: "https://dulcet-puffpuff-b87073.netlify.app/"},
        {name: "JS: Барабаны", link: "https://drumkit-adilet.netlify.app/"},
        {name: "JS: Случайная генерация", link: "https://random-adilet.netlify.app/"},
        {name: "JS: Котики", link: "https://admirable-clafoutis-a924b9.netlify.app/"},
        {name: "REACT: Список дел", link: "https://todo-adilet.netlify.app/"},
        {name: "REACT: Веб-консоль", link: "https://webshell-adilet.netlify.app/"},
        {name: "REACT: Интернет-магазин одежды", link: "https://www.youtube.com/watch?v=xGV0m7Y22co&t=22s"},
      ],
      subtitle:
        "Delivering a robust dashboard and interactive capabilities for efficient warehouse management",
      featured: true,
      url: "https://warehouse-planning-tool.onrender.com/",
      github: "https://github.com/AleksandrRiabov/wpt",
      technologies: [
        "React.Js",
        "TypeScript",
        "Node.Js (Express)",
        "MongoDB Atlas",
        "MaterialUI",
        "Recharts.js",
        "Date-fns",
        "react-router",
        "Firebase Authentication",
        "Deployed on render.com",
      ],
      imgSmall: wptSmall,
      imgMedium: wptMedium,
      imgLarge: projects,
      imgXl: wptXL,
      desc: "Проекты, которые я писал чтобы практиковать свой JavaScript",
      paragraphs: [
        "In the dynamic world of logistics, warehouses often collaborate with external distributors, emphasizing the need for timely trailer requests. This demands foresight, striking a balance between excess and shortage. The WPT app offers a visionary solution, reshaping estimation accuracy. Embrace this shift, take immediate action, and eliminate uncertainties in trailer requisition.",
      ],
    },
    {
      name: funny2,
      title: "Funny Gaz",
      haveLink: true,
      isKwork: true,
      subtitle:
        "Delivering a robust dashboard and interactive capabilities for efficient warehouse management",
      featured: true,
      url: "https://warehouse-planning-tool.onrender.com/",
      github: "https://github.com/AleksandrRiabov/wpt",
      technologies: [
        "React.Js",
        "TypeScript",
        "Node.Js (Express)",
        "MongoDB Atlas",
        "MaterialUI",
        "Recharts.js",
        "Date-fns",
        "react-router",
        "Firebase Authentication",
        "Deployed on render.com",
      ],
      imgSmall: wptSmall,
      imgMedium: wptMedium,
      imgLarge: funny,
      imgXl: wptXL,
      desc: "Интернет-магазин по продаже гелиевого газа. Сделал для друга и использовал Wordpress в связке с WooCommerce.",
      paragraphs: [
        "In the dynamic world of logistics, warehouses often collaborate with external distributors, emphasizing the need for timely trailer requests. This demands foresight, striking a balance between excess and shortage. The WPT app offers a visionary solution, reshaping estimation accuracy. Embrace this shift, take immediate action, and eliminate uncertainties in trailer requisition.",
      ],
    },
    {
      name: "https://ui-ux-design.ru",
      title: "UI-UX Дизайнер",
      isKwork: true,
      haveLink: true,
      subtitle:
        "Delivering a robust dashboard and interactive capabilities for efficient warehouse management",
      featured: true,
      url: "https://warehouse-planning-tool.onrender.com/",
      github: "https://github.com/AleksandrRiabov/wpt",
      technologies: [
        "React.Js",
        "TypeScript",
        "Node.Js (Express)",
        "MongoDB Atlas",
        "MaterialUI",
        "Recharts.js",
        "Date-fns",
        "react-router",
        "Firebase Authentication",
        "Deployed on render.com",
      ],
      imgSmall: wptSmall,
      imgMedium: wptMedium,
      imgLarge: uxui,
      imgXl: wptXL,
      desc: "Сайт-визитка на Vue.js с использованием Wordpress.",
      paragraphs: [
        "In the dynamic world of logistics, warehouses often collaborate with external distributors, emphasizing the need for timely trailer requests. This demands foresight, striking a balance between excess and shortage. The WPT app offers a visionary solution, reshaping estimation accuracy. Embrace this shift, take immediate action, and eliminate uncertainties in trailer requisition.",
      ],
    },
    {
      name: "https://youtu.be/WqQv2Uj_H3c",
      title: "Проведение ОСС",
      isKwork: false,
      haveLink: false,
      subtitle:
        "Delivering a robust dashboard and interactive capabilities for efficient warehouse management",
      featured: true,
      url: "https://warehouse-planning-tool.onrender.com/",
      github: "https://github.com/AleksandrRiabov/wpt",
      technologies: [
        "React.Js",
        "TypeScript",
        "Node.Js (Express)",
        "MongoDB Atlas",
        "MaterialUI",
        "Recharts.js",
        "Date-fns",
        "react-router",
        "Firebase Authentication",
        "Deployed on render.com",
      ],
      imgSmall: wptSmall,
      imgMedium: wptMedium,
      imgLarge: oss,
      imgXl: wptXL,
      desc: "Landing page созданный на конструкторе Tilda",
      paragraphs: [
        "In the dynamic world of logistics, warehouses often collaborate with external distributors, emphasizing the need for timely trailer requests. This demands foresight, striking a balance between excess and shortage. The WPT app offers a visionary solution, reshaping estimation accuracy. Embrace this shift, take immediate action, and eliminate uncertainties in trailer requisition.",
      ],
    },
    {
      name: "https://taliya-laser.netlify.app/",
      title: "Лазерная эпиляция",
      isKwork: false,
      haveLink: true,
      subtitle:
        "Delivering a robust dashboard and interactive capabilities for efficient warehouse management",
      featured: true,
      url: "https://warehouse-planning-tool.onrender.com/",
      github: "https://github.com/AleksandrRiabov/wpt",
      technologies: [
        "React.Js",
        "TypeScript",
        "Node.Js (Express)",
        "MongoDB Atlas",
        "MaterialUI",
        "Recharts.js",
        "Date-fns",
        "react-router",
        "Firebase Authentication",
        "Deployed on render.com",
      ],
      imgSmall: wptSmall,
      imgMedium: wptMedium,
      imgLarge: laser,
      imgXl: wptXL,
      desc: "Landing page написанный на HTML, CSS, JS",
      paragraphs: [
        "In the dynamic world of logistics, warehouses often collaborate with external distributors, emphasizing the need for timely trailer requests. This demands foresight, striking a balance between excess and shortage. The WPT app offers a visionary solution, reshaping estimation accuracy. Embrace this shift, take immediate action, and eliminate uncertainties in trailer requisition.",
      ],
    },
    {
      name: "https://youtu.be/WqQv2Uj_H3c",
      title: "Продюссерский центр",
      isKwork: false,
      haveLink: true,
      subtitle:
        "Delivering a robust dashboard and interactive capabilities for efficient warehouse management",
      featured: true,
      url: "https://warehouse-planning-tool.onrender.com/",
      github: "https://github.com/AleksandrRiabov/wpt",
      technologies: [
        "React.Js",
        "TypeScript",
        "Node.Js (Express)",
        "MongoDB Atlas",
        "MaterialUI",
        "Recharts.js",
        "Date-fns",
        "react-router",
        "Firebase Authentication",
        "Deployed on render.com",
      ],
      imgSmall: wptSmall,
      imgMedium: wptMedium,
      imgLarge: legce,
      imgXl: wptXL,
      desc: "Landing page написанный на HTML, CSS, JS с использованием Anime.js для создания анимации чисел",
      paragraphs: [
        "In the dynamic world of logistics, warehouses often collaborate with external distributors, emphasizing the need for timely trailer requests. This demands foresight, striking a balance between excess and shortage. The WPT app offers a visionary solution, reshaping estimation accuracy. Embrace this shift, take immediate action, and eliminate uncertainties in trailer requisition.",
      ],
    },
    {
      name: "https://youtu.be/WqQv2Uj_H3c",
      title: "Международный Университет им. К.Ш. Токтомаматова",
      isKwork: false,
      haveLink: false,
      subtitle:
        "Delivering a robust dashboard and interactive capabilities for efficient warehouse management",
      featured: true,
      url: "https://warehouse-planning-tool.onrender.com/",
      github: "https://github.com/AleksandrRiabov/wpt",
      technologies: [
        "React.Js",
        "TypeScript",
        "Node.Js (Express)",
        "MongoDB Atlas",
        "MaterialUI",
        "Recharts.js",
        "Date-fns",
        "react-router",
        "Firebase Authentication",
        "Deployed on render.com",
      ],
      imgSmall: wptSmall,
      imgMedium: wptMedium,
      imgLarge: mnu,
      imgXl: wptXL,
      desc: "Исправление мелких багов по верстке, а также редизайн сайта",
      paragraphs: [
        "In the dynamic world of logistics, warehouses often collaborate with external distributors, emphasizing the need for timely trailer requests. This demands foresight, striking a balance between excess and shortage. The WPT app offers a visionary solution, reshaping estimation accuracy. Embrace this shift, take immediate action, and eliminate uncertainties in trailer requisition.",
      ],
    },
  ],
  socialLinks: [
    {
      name: "GitHub",
      icon: <GitHub fontSize="inherit" />,
      url: "https://github.com/AleksandrRiabov",
      message: "Follow for open-source projects",
    },
    {
      name: "LinkedIn",
      icon: <LinkedIn fontSize="inherit" />,
      url: "https://www.linkedin.com/in/aleksandr-riabov",
      message: "Let's connect on LinkedIn",
    },
  ],
  links: [
    {
      name: "Home",
      url: "/",
      navLink: true,
    },
    {
      name: "Portfolio",
      url: "/portfolio",
      message: "View Alek's previous work",
      navLink: true,
    },
    {
      name: "About",
      url: "/about",
      message: "Learn about Alek's skills",
      navLink: true,
    },
    {
      name: "Get In Touch",
      url: "/contacts",
      message: "Send a general message",
      navLink: false,
    },
  ],
};

export default data;
